name: Test Slack

on:
  push:
    branches: [ test ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
      - uses: actions/checkout@v2

      - name: Notify
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          echo $SLACK_TOKEN CHANNEL_ID
          chmod +x .slack-notification
          ./.slack-notification
