name: Test Slack

on:
  push:
    branches: [ test ]

  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Notify
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          channel: money-expenses
          channel_id: ${{ secrets.CHANNEL_ID }}
          slack-bot-token: ${{ secrets.SLACK_TOKEN }}
