name: Build & Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
      - uses: actions/checkout@v2

      - name: Envinfo
        run: npx envinfo

      - name: Install Modules
        run: |
          yarn install
          npx jetify

      - name: Build App
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Slack Notify
        if: success()
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          run: |
            chmod +x .slack-notification
            ./.slack-notification

      - name: Send App to Slack
        if: success()
        env:
          ARM64_V8A: ${{ secrets.ARM64_V8A }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          curl -v -F file=@$ARM64_V8A -F channels=$CHANNEL_ID -F token=$SLACK_TOKEN https://slack.com/api/files.upload
